# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.provision "file", source: "elasticsearch-6.7.0.zip.sha512", destination: "~/elasticsearch-6.7.0.zip.sha512"
    config.vm.provision "file", source: "elasticsearch.yml", destination: "~/tmp/elasticsearch/elasticsearch.yml"
    config.vm.provision "file", source: "jvm.options", destination: "~/tmp/elasticsearch/jvm.options"
    config.vm.provision "file", source: "limits.conf", destination: "~/tmp/etc/security/limits.conf"
    config.vm.provision "file", source: "sudo", destination: "~/tmp/etc/pam.d/sudo"
    config.vm.provision "file", source: "sysctl.conf", destination: "~/tmp/etc/sysctl.conf"
    config.vm.provision "file", source: ".env", destination: "~/.env"
    config.vm.provision "file", source: "hosts", destination: "~/tmp/hosts"

    config.vm.provision "shell", path: "provision.sh", privileged: false



    config.vm.define "node-1" do |a|
        a.vm.box = "ubuntu/xenial64"
        a.vm.network "private_network", ip: "192.168.33.10"
        a.vm.provider "virtualbox" do |vb|
            vb.memory = 8192
            vb.cpus = 2
        end
        a.vm.provision "shell", inline: <<-SHELL
            export ES_NODE_NAME="node-1"
        SHELL
    end

    config.vm.define "node-2" do |a|
        a.vm.box = "ubuntu/xenial64"
        a.vm.network "private_network", ip: "192.168.33.20"
        a.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 2
        end
        a.vm.provision "shell", inline: <<-SHELL
            export ES_NODE_NAME="node-2"
            ping -c 4 node-1
        SHELL
    end
end
